"""Initial schema

Revision ID: b3b7c2359a65
Revises: 
Create Date: 2025-06-06 12:35:05.149320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b7c2359a65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urlrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('Have_IP', sa.Integer(), nullable=False),
    sa.Column('Have_At', sa.Integer(), nullable=False),
    sa.Column('URL_Length', sa.Integer(), nullable=False),
    sa.Column('URL_Depth', sa.Integer(), nullable=False),
    sa.Column('Redirection', sa.Integer(), nullable=False),
    sa.Column('https_Domain', sa.Integer(), nullable=False),
    sa.Column('TinyURL', sa.Integer(), nullable=False),
    sa.Column('Prefix_Suffix', sa.Integer(), nullable=False),
    sa.Column('DNS_Record', sa.Integer(), nullable=False),
    sa.Column('Web_Traffic', sa.Integer(), nullable=False),
    sa.Column('Domain_Age', sa.Integer(), nullable=False),
    sa.Column('Domain_End', sa.Integer(), nullable=False),
    sa.Column('iFrame', sa.Integer(), nullable=False),
    sa.Column('Mouse_Over', sa.Integer(), nullable=False),
    sa.Column('Right_Click', sa.Integer(), nullable=False),
    sa.Column('Web_Forwards', sa.Integer(), nullable=False),
    sa.Column('Suspicious_Words', sa.Integer(), nullable=False),
    sa.Column('Suspicious_Patterns', sa.Integer(), nullable=False),
    sa.Column('Have_Currency', sa.Integer(), nullable=False),
    sa.Column('GoogleIndex', sa.Integer(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    # sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urlrecord')
    # ### end Alembic commands ###
